import static org.junit.Assert.assertTrue;

import org.junit.Test;

import com.ajt.loggin.Library;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'alist' at '16/04/17 18:05' with Gradle 2.14.1
 *
 * @author alist, @date 16/04/17 18:05
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
